### ISSUE TITLE
Return of 'ValueError: scatter requires x column to be numeric'

### ISSUE THREAD

**Issue by benkrikler** [FAST-HEP/fast-plotter#3]
**Imported from [gitlab issue 3](https://gitlab.cern.ch/fast-hep/public/fast-plotter/issues/3)**

CSV's are attached - seems to be an issue with all of them

```
(chip_env) [zw18769@soolin updated_combined_signals]$ fast_plotter -s ".*" -o ~/CHIP/analysis/output/MC_signals/combined_signal_5-12-18/ -l 41800 -w weight_nominal ~/CHIP/analysis/output/MC_signals/combined_signal/tbl_dataset.leadJet_pt.leadJet_eta--weight_nominal.csv 

fast_plotter - INFO - Processing: /users/zw18769/CHIP/analysis/output/MC_signals/combined_signal/tbl_dataset.leadJet_pt.leadJet_eta--weight_nominal.csv

Traceback (most recent call last):
  File "/users/zw18769/.local/bin/fast_plotter", line 11, in <module>
    load_entry_point('fast-plotter', 'console_scripts', 'fast_plotter')()
  File "/users/zw18769/CHIP/fast-plotter/fast_plotter/__main__.py", line 49, in main
    process_one_file(infile, args)
  File "/users/zw18769/CHIP/fast-plotter/fast_plotter/__main__.py", line 71, in process_one_file
    data=args.data, signal=args.signal, scale_sims=args.lumi, yscale=args.yscale)
  File "/users/zw18769/CHIP/fast-plotter/fast_plotter/plotting.py", line 21, in plot_all
    plot = plot_1d_many(projected, data=data, signal=signal, dataset_col=dataset_col, yscale=yscale, scale_sims=scale_sims)
  File "/users/zw18769/CHIP/fast-plotter/fast_plotter/plotting.py", line 99, in plot_1d_many
    plot_ratio(summed_data, summed_sims, x=x_axis, y=y, yvar=yvar, ax=summary_ax)
  File "/users/zw18769/CHIP/fast-plotter/fast_plotter/plotting.py", line 135, in plot_ratio
    ratio.reset_index().plot.scatter(x=x, y="Data / MC", yerr="err", ax=ax)
  File "/users/zw18769/.local/lib/python2.7/site-packages/pandas/plotting/_core.py", line 3461, in scatter
    return self(kind='scatter', x=x, y=y, c=c, s=s, **kwds)
  File "/users/zw18769/.local/lib/python2.7/site-packages/pandas/plotting/_core.py", line 2941, in __call__
    sort_columns=sort_columns, **kwds)
  File "/users/zw18769/.local/lib/python2.7/site-packages/pandas/plotting/_core.py", line 1977, in plot_frame
    **kwds)
  File "/users/zw18769/.local/lib/python2.7/site-packages/pandas/plotting/_core.py", line 1743, in _plot
    kind=kind, **kwds)
  File "/users/zw18769/.local/lib/python2.7/site-packages/pandas/plotting/_core.py", line 845, in __init__
    super(ScatterPlot, self).__init__(data, x, y, s=s, **kwargs)
  File "/users/zw18769/.local/lib/python2.7/site-packages/pandas/plotting/_core.py", line 820, in __init__
    raise ValueError(self._kind + ' requires x column to be numeric')

ValueError: scatter requires x column to be numeric`
```

[tbl_dataset.leadJet_eta--weight_nominal.csv](/uploads/bad7ad476747f7ef37da6a9304885af9/tbl_dataset.leadJet_eta--weight_nominal.csv)

[cuts_signal_selection-.csv](/uploads/11d471a149f9fac4167b27d9b5484a47/cuts_signal_selection-.csv)

[tbl_dataset.met--weight_nominal.csv](/uploads/907f3c263b565151189a164af92011c3/tbl_dataset.met--weight_nominal.csv)

[tbl_dataset.leadJet_pt.leadJet_eta--weight_nominal.csv](/uploads/e8b4e3efc4eca9cd3ef379e1f3195df9/tbl_dataset.leadJet_pt.leadJet_eta--weight_nominal.csv)

[tbl_dataset.njet.nbjet--weight_nominal.csv](/uploads/cc8764aee9a617617eda26c16402c579/tbl_dataset.njet.nbjet--weight_nominal.csv)

[tbl_dataset.sublJet_eta--weight_nominal.csv](/uploads/c007c1747356074f9dc31e9ebad31b26/tbl_dataset.sublJet_eta--weight_nominal.csv)

[tbl_dataset.sublJet_pt.sublJet_eta--weight_nominal.csv](/uploads/bf5b51891b812539d1ab938870f9d461/tbl_dataset.sublJet_pt.sublJet_eta--weight_nominal.csv)

**Comment by benkrikler** [comment]
**On 2018-12-07 Benjamin Krikler (bkrikler) wrote:**

changed the description

**Comment by benkrikler** [comment]
**On 2018-12-07 David Anthony (danthony) wrote:**

changed the description

**Comment by benkrikler** [comment]
**On 2018-12-07 David Anthony (danthony) wrote:**

changed the description

**Comment by benkrikler** [comment]
**On 2018-12-07 David Anthony (danthony) wrote:**

changed the description

**Comment by benkrikler** [comment]
**On 2018-12-07 David Anthony (danthony) wrote:**

changed the description

**Comment by benkrikler** [comment]
**On 2018-12-07 David Anthony (danthony) wrote:**

changed the description

**Comment by benkrikler** [comment]
**On 2018-12-12 Benjamin Krikler (bkrikler) wrote:**

mentioned in merge request [gitlab:!6](https://gitlab.cern.ch/fast-hep/public/fast-plotter/merge_requests/6)

**Comment by benkrikler** [comment]
**On 2018-12-12 Benjamin Krikler (bkrikler) wrote:**

closed via merge request [gitlab:!6](https://gitlab.cern.ch/fast-hep/public/fast-plotter/merge_requests/6)

**Comment by benkrikler** [comment]
**On 2018-12-12 Benjamin Krikler (bkrikler) wrote:**

mentioned in commit 0598dbceac1876561173b991389c14b4f78ff9dd

**Comment by benkrikler** [comment]
**On 2018-12-12 Benjamin Krikler (bkrikler) wrote:**

This was automatically closed in [gitlab:!6](https://gitlab.cern.ch/fast-hep/public/fast-plotter/merge_requests/6) but if this is still an issue, feel free to reopen.

**Comment by benkrikler** [comment]
**On 2018-12-12 David Anthony (danthony) wrote:**

Cheers, working fine now
